[www]
user = www-data
group = www-data

listen = 127.0.0.1:9000

pm = dynamic
pm.max_children = 20
pm.start_servers = 5
pm.min_spare_servers = 3
pm.max_spare_servers = 10
pm.max_requests = 500

; Status page (for monitoring)
pm.status_path = /fpm-status

; Slow log
slowlog = /var/log/php-fpm-slow.log
request_slowlog_timeout = 10s

; Clear environment
clear_env = no
